name: Basic CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  # For nektos/act to work (local testing)
  IS_LOCAL: "${{ secrets.IS_LOCAL == 'true' }}"
jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: For act to work (local testing)
        if: ${{ env.IS_LOCAL == 'true' }}
        run: npm -g install yarn

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check and build
        run: yarn build

      - name: Run ESLint
        run: yarn lint

      - name: Check Prettier formatting
        run: yarn format:check

      - name: Run e2e tests
        run: yarn test

      - name: Check build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build output directory 'dist' not found"
            exit 1
          fi

          if [ ! -f "dist/index.js" ]; then
            echo "Main build file 'dist/index.js' not found"
            exit 1
          fi

          if [ ! -f "dist/index.d.ts" ]; then
            echo "Type definitions 'dist/index.d.ts' not found"
            exit 1
          fi

          echo "Build output verified successfully"
